<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Billing</name>
   <tag></tag>
   <elementGuidId>8ab287a6-9c63-4a18-9bfc-4aa408d3a026</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='title-billing']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#title-billing</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2c5a9b38-4da3-4f87-8cb9-0834ebbeb757</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>automation_id</name>
      <type>Main</type>
      <value>div_defaultHubBillingPageLink</value>
      <webElementGuid>a6f2728d-6e29-4c56-b9b5-88584c2ad030</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>section-heading</value>
      <webElementGuid>d575a114-fb00-48af-9401-cd9ddacd0b03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>title-billing</value>
      <webElementGuid>4f452d7d-aff2-48b8-be57-9d79fb4defe9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Billing</value>
      <webElementGuid>b994f392-3959-417a-905b-e96081fa5940</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;title-billing&quot;)</value>
      <webElementGuid>12b3e635-4754-4a88-aaa8-39cca0ed8e9c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='title-billing']</value>
      <webElementGuid>21ed7210-5839-4371-8e04-24415ec0ce01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainHubContentHome']/div[2]/div/div[2]/div/div</value>
      <webElementGuid>58280af7-8832-4714-b739-f9d7707da3ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daily Close'])[1]/following::div[3]</value>
      <webElementGuid>fba04ed6-93cc-4fbe-a504-5d8a8dde37b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Collection Calls'])[1]/following::div[3]</value>
      <webElementGuid>0b115b3d-bf39-4df5-b9be-08a134f5d63c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invoices'])[2]/preceding::div[1]</value>
      <webElementGuid>36899225-0cf9-46ee-a74d-d1ac4d53d0c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ACH'])[1]/preceding::div[1]</value>
      <webElementGuid>83af7fc5-9395-4afc-a885-49be94d808b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div[2]/div/div</value>
      <webElementGuid>c8363960-1197-4994-893a-efee99447a4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'title-billing' and (text() = 'Billing' or . = 'Billing')]</value>
      <webElementGuid>ce58fbe2-4c66-4d40-b196-542ed3f4c991</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
