<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ACH</name>
   <tag></tag>
   <elementGuidId>db6542d0-9dca-4b46-8017-d2e46485d081</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;ga('send', 'event', 'HomeMenus', 'click', 'ACH');&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>25646764-7810-4e7c-aa93-0b76853a6aff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>automation_id</name>
      <type>Main</type>
      <value>lnk_defaultBillingSubMenu</value>
      <webElementGuid>3f79e39d-9005-4fe1-a30d-edfaafe7315d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/SLQA/HS/Operations/Batch/ProcessAch</value>
      <webElementGuid>a06c6b1e-3b1b-4686-86bf-f0e485425db8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menulink</value>
      <webElementGuid>2a637f27-8387-482f-ba7d-61630546791e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>ga('send', 'event', 'HomeMenus', 'click', 'ACH');</value>
      <webElementGuid>1184945e-412c-4e11-989c-9ef3bc3e522c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                                ACH
                                                            </value>
      <webElementGuid>14be0fd3-cceb-4a21-889d-e2b2ce9a369e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billingContainer&quot;)/div[@class=&quot;section-title&quot;]/a[@class=&quot;menulink&quot;]</value>
      <webElementGuid>98312cd1-9d84-460d-b629-38ef0f92ccad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;ga('send', 'event', 'HomeMenus', 'click', 'ACH');&quot;]</value>
      <webElementGuid>906c7bd0-9817-4275-a520-027684c220a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='billingContainer']/div/a[2]</value>
      <webElementGuid>346b576a-6a51-45f3-806b-726691b42cd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'ACH')]</value>
      <webElementGuid>4e98e693-af88-4c5a-bb7d-3b6d981ef081</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invoices'])[2]/following::a[1]</value>
      <webElementGuid>8f52d990-cb14-4909-9708-aeb300dc6639</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Billing'])[1]/following::a[2]</value>
      <webElementGuid>bfe2c265-4bc5-425f-b43c-e52d25c75360</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Credit Cards'])[1]/preceding::a[1]</value>
      <webElementGuid>a34f4347-67fa-40da-936f-f1635342281f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reports'])[1]/preceding::a[2]</value>
      <webElementGuid>1591e1a4-68cb-4869-af5e-0985ec7fdb94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ACH']/parent::*</value>
      <webElementGuid>818a29ab-b65c-4d24-a241-444ac708623f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/SLQA/HS/Operations/Batch/ProcessAch')]</value>
      <webElementGuid>a80ebdbc-9cb0-42bb-89e3-5b945c34c0e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/a[2]</value>
      <webElementGuid>5c3186f3-e52c-4cf7-be18-e62efcb592a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/SLQA/HS/Operations/Batch/ProcessAch' and (text() = '
                                                                ACH
                                                            ' or . = '
                                                                ACH
                                                            ')]</value>
      <webElementGuid>3230fcb7-f941-4a0c-8763-d6c09f3ff80c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
