<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Lead to Lease</name>
   <tag></tag>
   <elementGuidId>2c0d3ba3-261e-4593-b358-5fe664530735</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='LeadToLeaseViewContainer']/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.page-title.blue</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>96689de4-ebbd-4d55-9b15-63c0782d7140</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page-title blue</value>
      <webElementGuid>f8c91f65-65b9-41ec-bb35-ad79b2b07c87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lead to Lease</value>
      <webElementGuid>a21928f5-af1a-42d5-bda8-49e08f91f033</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LeadToLeaseViewContainer&quot;)/div[@class=&quot;container-fluid full-height ng-scope&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;page-title blue&quot;]</value>
      <webElementGuid>e976aa5d-16c9-46b9-9f29-6d69ccb375bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='LeadToLeaseViewContainer']/div/div/div/div</value>
      <webElementGuid>49f9a1c8-96fb-40ae-83d5-d277ff3791d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div</value>
      <webElementGuid>64fcba6a-694d-4c46-8c50-8e7c27cf14b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Lead to Lease' or . = 'Lead to Lease')]</value>
      <webElementGuid>8d67cddd-25b3-46fb-b296-bf7ef5b3acb5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
