<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>StudioAssistScriptSuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>3feabf65-f941-4f41-bef6-a17e63655d66</testSuiteGuid>
   <testCaseLink>
      <guid>1c777d17-27f2-4bdf-af32-979241522df1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/StudioAsisit/Generate Code UserCase_1</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7707fdc3-233f-44d9-91ab-47918d5e9af1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>69578dd4-8337-45bc-975c-f3e8d01c7f9d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>16bdac73-d3f6-4edc-a316-38e9788a9a28</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>03d0324f-b892-40e9-b03e-4a830c95fc32</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>64fd8433-0c95-4927-8213-227a37145309</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/StudioAsisit/Generate Code UserCase_2</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>62927d83-2b52-487b-8504-e415c684af1b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>66f77cb1-4ae8-4727-925f-d0e3de611eda</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4bc425d-7c68-4edb-a840-e0767e2d2e14</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eb55560f-ed73-44ec-a48b-29565b0f5965</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6f121f2e-e20d-485d-b65c-07c10f39471f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/StudioAsisit/Generate Code UserCase_3</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4c339e29-228a-460e-aadb-c7145ad813ff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>506d79da-dbba-429b-ad13-5e9e759466ea</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>90f7c60c-4c0c-4413-a9fd-67e80a87b73f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/StudioAsisit/Generate Code UserCase_4</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9f2a6921-643d-4337-b70f-260c2da0ec97</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b0857648-bba3-4ffa-ae9b-3576827b6fc5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fa952d83-a69b-4ce1-beb8-b19b1e0f91d4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/StudioAsisit/Generate Code UserCase_5</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2639baf7-b219-44a9-97ad-ad515bae371a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c207b994-3482-44eb-acfa-7ba28b74cff6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4eab1b74-3b53-4c5c-8077-bfff28b55429</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/StudioAsisit/Generate Code UserCase_6</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4f1d58a3-551e-4b38-a210-9690ae1cf2a6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d2f405a1-d341-4d02-a925-fa644299548a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c80d93f9-4b02-42b6-9ee6-57b4ddc51bf1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dec06758-0aa9-4cf6-bea6-261c1588f375</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4e87cc82-8258-46ec-aed9-b1d34ef7c194</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/StudioAsisit/Generate Code UserCase_7</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c2d3da8e-4ea6-4d80-81b4-4a83f3402a99</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1aec6960-f768-49fb-88a5-adf15a1f6b82</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>03031382-6f46-43be-9984-7a08fc40f050</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/StudioAsisit/Generate Code UserCase_8</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>24e0735f-a7e4-4c9f-99d9-1bc586fc5d29</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0ae39885-388f-4022-880d-da089aa84516</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
