<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_28</name>
   <tag></tag>
   <elementGuidId>5a76946d-7426-4661-93c6-22470a3f5d19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[79]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b6b6c524-324b-4eb9-bf5a-85b3841c2878</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1ba7ecb3-229d-4e60-9ea6-11ca003f2d4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>28, Friday, February 2025. Available. Select as check-in date.</value>
      <webElementGuid>75256c3c-c493-45dd-8eac-bb3332716865</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d11exu1w atm_vy_1osqo2v atm_1w_gbua2q atm_mk_h2mmj6 atm_9s_1txwivl atm_h_1h6ojuz atm_fc_1h6ojuz atm_fb_1cl4t0h atm_c8_dlk8xv atm_cs_10d11i2 atm_7l_dezgoh atm_9j_tlke0l atm_vb_glywfm atm_70_glywfm atm_2d_n7od8j atm_3f_n7od8j atm_lb_n7od8j atm_lh_n7od8j atm_vy_1osqo2v_vmtskl atm_e2_1osqo2v_vmtskl atm_mk_stnw88_vmtskl atm_92_1yyfdc7_vmtskl atm_5j_1ssbidh_vmtskl atm_wq_1mrwo0b_vmtskl atm_3f_11x2w5_1rqz0hn_uv4tnr atm_kd_glywfm_1w3cfyq atm_3f_glywfm_e4a3ld atm_l8_idpfg4_e4a3ld atm_gi_idpfg4_e4a3ld atm_3f_glywfm_1r4qscq atm_kd_glywfm_6y7yyg atm_uc_aaiy6o_9xuho3 atm_70_1kppo7g_9xuho3 atm_uc_glywfm_9xuho3_1rrf6b5 atm_kd_glywfm_pfnrn2_1oszvuo atm_3f_glywfm_1icshfk_1oszvuo atm_l8_idpfg4_1icshfk_1oszvuo atm_gi_idpfg4_1icshfk_1oszvuo atm_3f_glywfm_b5gff8_1oszvuo atm_kd_glywfm_2by9w9_1oszvuo atm_uc_aaiy6o_1buez3b_1oszvuo atm_70_1kppo7g_1buez3b_1oszvuo atm_uc_glywfm_1buez3b_1o31aam d1h3s0zq atm_mj_1wugsn5 dir dir-ltr</value>
      <webElementGuid>e8cb5238-ca0a-41ee-af07-81e682fd1617</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state--date-string</name>
      <type>Main</type>
      <value>2025-02-28</value>
      <webElementGuid>6a9c2b23-6f07-4393-bbbd-2a417e8e5ff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>443a4dd4-79fb-440d-8a57-73845f8b0832</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>28</value>
      <webElementGuid>b226331b-b3e7-47cb-b3e6-aa9f13557531</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panel--tabs--0&quot;)/div[@class=&quot;d1xjigzy atm_h_1h6ojuz__7pk1ck atm_9s_1txwivl__7pk1ck atm_ar_1bp4okc__7pk1ck atm_fc_1h6ojuz__7pk1ck dir dir-ltr&quot;]/div[@class=&quot;h1yby4o2 atm_9s_1o8liyq atm_mk_h2mmj6 h12enwjs atm_vy_1a0j60c atm_gz_vgba9w atm_h0_vgba9w dir dir-ltr&quot;]/div[4]/div[@class=&quot;e46z8ty atm_l0_15vqwwr atm_vy_1osqo2v dir dir-ltr&quot;]/div[@class=&quot;ecjc60a atm_9s_1txwivl atm_uq_1e032xh atm_uv_1ytfnp0 atm_h_v2br90 dir dir-ltr&quot;]/div[@class=&quot;m1uqgy7e atm_9s_11p5wf0 atm_dz_1u8mbql atm_n5_yh40bf atm_vy_1osqo2v atm_l8_1w78mzc atm_ks_zryt35 h1pfdthe atm_gz_d4y9na atm_h0_d4y9na dir dir-ltr&quot;]/button[@class=&quot;d11exu1w atm_vy_1osqo2v atm_1w_gbua2q atm_mk_h2mmj6 atm_9s_1txwivl atm_h_1h6ojuz atm_fc_1h6ojuz atm_fb_1cl4t0h atm_c8_dlk8xv atm_cs_10d11i2 atm_7l_dezgoh atm_9j_tlke0l atm_vb_glywfm atm_70_glywfm atm_2d_n7od8j atm_3f_n7od8j atm_lb_n7od8j atm_lh_n7od8j atm_vy_1osqo2v_vmtskl atm_e2_1osqo2v_vmtskl atm_mk_stnw88_vmtskl atm_92_1yyfdc7_vmtskl atm_5j_1ssbidh_vmtskl atm_wq_1mrwo0b_vmtskl atm_3f_11x2w5_1rqz0hn_uv4tnr atm_kd_glywfm_1w3cfyq atm_3f_glywfm_e4a3ld atm_l8_idpfg4_e4a3ld atm_gi_idpfg4_e4a3ld atm_3f_glywfm_1r4qscq atm_kd_glywfm_6y7yyg atm_uc_aaiy6o_9xuho3 atm_70_1kppo7g_9xuho3 atm_uc_glywfm_9xuho3_1rrf6b5 atm_kd_glywfm_pfnrn2_1oszvuo atm_3f_glywfm_1icshfk_1oszvuo atm_l8_idpfg4_1icshfk_1oszvuo atm_gi_idpfg4_1icshfk_1oszvuo atm_3f_glywfm_b5gff8_1oszvuo atm_kd_glywfm_2by9w9_1oszvuo atm_uc_aaiy6o_1buez3b_1oszvuo atm_70_1kppo7g_1buez3b_1oszvuo atm_uc_glywfm_1buez3b_1o31aam d1h3s0zq atm_mj_1wugsn5 dir dir-ltr&quot;]</value>
      <webElementGuid>285fd62a-75ca-47db-a911-87130a135098</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[79]</value>
      <webElementGuid>9ae1dee4-df0b-42bf-a78b-99d428dcafcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='panel--tabs--0']/div/div/div[4]/div/div/div[2]/button[34]</value>
      <webElementGuid>420d478b-645c-4501-8f11-362cfffaa26b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sat'])[2]/following::button[69]</value>
      <webElementGuid>4445c5b5-78a1-4593-9c85-2176173a222f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fri'])[2]/following::button[69]</value>
      <webElementGuid>17312958-8f78-40f8-9491-9b61267b8b4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exact dates'])[1]/preceding::button[2]</value>
      <webElementGuid>efe75ddb-ed54-44ac-b336-e2e246799266</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='±1 day'])[1]/preceding::button[2]</value>
      <webElementGuid>a263986b-4b03-4f39-8dab-5312880cfdfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button[34]</value>
      <webElementGuid>7c721593-b834-4ce0-9d3a-07ca0586695d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '28' or . = '28')]</value>
      <webElementGuid>368e66f4-ccdf-4722-a427-0573854c23f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
