<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Where_query</name>
   <tag></tag>
   <elementGuidId>7d880b3b-422b-48dc-9464-ff18fb95f462</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='bigsearch-query-location-input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bigsearch-query-location-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>15f15fde-98cf-4847-9d82-7321ed248eb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>i18z192n atm_9s_1ulexfb atm_3f_idpfg4 atm_gi_idpfg4 atm_l8_idpfg4 atm_vy_1osqo2v atm_26_glywfm atm_c8_km0zk7 atm_g3_18khvle atm_fr_1m9t47k atm_cs_10d11i2 atm_7l_dezgoh atm_sq_1l2sidv atm_c8_km0zk7_17x46du atm_g3_18khvle_17x46du atm_fr_1m9t47k_17x46du atm_cs_6adqpa_17x46du atm_7l_j427c7_17x46du atm_c8_km0zk7_y5ttn9 atm_g3_18khvle_y5ttn9 atm_fr_1m9t47k_y5ttn9 atm_cs_6adqpa_y5ttn9 atm_7l_j427c7_y5ttn9 atm_c8_km0zk7_1k1obal atm_g3_18khvle_1k1obal atm_fr_1m9t47k_1k1obal atm_cs_6adqpa_1k1obal atm_7l_j427c7_1k1obal atm_c8_km0zk7_m14rgb atm_g3_18khvle_m14rgb atm_fr_1m9t47k_m14rgb atm_cs_6adqpa_m14rgb atm_7l_j427c7_m14rgb atm_c8_km0zk7_3ykvna atm_g3_18khvle_3ykvna atm_fr_1m9t47k_3ykvna atm_cs_6adqpa_3ykvna atm_7l_j427c7_3ykvna atm_9s_glywfm_16s2r6p atm_kd_glywfm_pfnrn2 atm_ll_1fwxnve_c2x6ez dir dir-ltr</value>
      <webElementGuid>25702e10-ac70-4713-968b-a2c0b7658291</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>9d368aef-6ead-4298-a298-aa132c39044b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>edc2cb1b-1465-48ac-af11-6a1e7c75f0f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>91914c63-48b3-4942-9fa3-01fdd5d083f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>56e46812-ea20-4fbc-a86b-3e8b4e4b11a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bigsearch-query-location-input</value>
      <webElementGuid>1b749157-9a9d-4e76-adbb-4b674a9d2e98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>query</value>
      <webElementGuid>b2d07735-8f36-472d-920c-793c8e9ca519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>e63318ec-9649-4c3a-b672-28d85b4d35bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>bigsearch-query-location-description</value>
      <webElementGuid>a8937093-59b7-44a8-8979-2ddfadf73849</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search destinations</value>
      <webElementGuid>433b6d0a-41d0-4e99-9efb-5d400e69cb1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>structured-search-input-field-query</value>
      <webElementGuid>d86382a3-1a61-4e29-84ac-09df44af8926</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>N</value>
      <webElementGuid>67d8e0ed-1917-4e51-9dad-e86e9e8ae9c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>bigsearch-query-location-listbox</value>
      <webElementGuid>ed1500f6-41c7-471e-bd4a-07148718d638</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>208fe853-b724-445a-8c81-42d886a24fe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>d696621c-45d7-44e3-bb22-8d7677f81efc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>3cb3b63d-0775-4f73-a9f5-a160c81305a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bigsearch-query-location-input&quot;)</value>
      <webElementGuid>d3205656-ea30-471e-928a-f09dfc5459c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='bigsearch-query-location-input']</value>
      <webElementGuid>909f5ac4-133a-4ac5-8611-bd4fc1ab7c9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search-tabpanel']/div/div/div/label/div/input</value>
      <webElementGuid>9c90597b-c542-4e7f-be0a-0abcdf8a8c96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/div/input</value>
      <webElementGuid>a37c8c27-e8db-47b8-8b20-40c43df70443</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'bigsearch-query-location-input' and @name = 'query' and @type = 'search' and @placeholder = 'Search destinations']</value>
      <webElementGuid>65f34ced-2c7b-4bc5-ab73-c48a67c8e6e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
