<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_The Corp Code field is required</name>
   <tag></tag>
   <elementGuidId>f0a88645-f71a-494a-b172-96c15e4dee65</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='Client_CorpCode-error']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Client_CorpCode-error</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c1347b00-fedc-445b-bd28-87e26e930d14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Client_CorpCode-error</value>
      <webElementGuid>30de53d2-7104-492e-8705-39c812f0d2c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>The Corp Code field is required.</value>
      <webElementGuid>1f6cf1e6-a0fc-475c-9c3f-bd1578e3691b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Client_CorpCode-error&quot;)</value>
      <webElementGuid>2f73fe34-eb16-4e91-8a51-2c0bf5335495</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='Client_CorpCode-error']</value>
      <webElementGuid>1b22d253-108f-40fc-8ace-82a34206323d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='loginform']/div/div/form/div/div[2]/div/div[2]/div/span/span</value>
      <webElementGuid>c0aff4d6-cd92-49f1-b89d-9063f2e232e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Corp Code'])[1]/following::span[2]</value>
      <webElementGuid>fe177930-6cf6-4e7a-afac-ae0aced1de6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SiteLink Web Edition'])[1]/following::span[3]</value>
      <webElementGuid>260dc9fd-f6ab-4420-a0fb-4ac5b0bf35bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Location Code'])[1]/preceding::span[1]</value>
      <webElementGuid>36809806-8a75-4fed-8ee3-190204cfa6a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The Location Code field is required.'])[1]/preceding::span[1]</value>
      <webElementGuid>628374dd-a00b-4398-9b80-932b2de1b7c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='The Corp Code field is required.']/parent::*</value>
      <webElementGuid>3ba1a004-04f5-4406-a6b2-3bfb953c90a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span</value>
      <webElementGuid>99680a59-49ad-4d9e-b7f0-627cda964216</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'Client_CorpCode-error' and (text() = 'The Corp Code field is required.' or . = 'The Corp Code field is required.')]</value>
      <webElementGuid>ff87975d-1de3-4ee9-96be-51b5e2f6fe83</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
