<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Corp Code_Client.CorpCode</name>
   <tag></tag>
   <elementGuidId>dcdce79f-9a0b-4803-89d7-b63ca784b547</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Client_CorpCode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Client_CorpCode</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f719f915-ce66-4171-b4fc-9836141de2bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>automation_id</name>
      <type>Main</type>
      <value>txt_clientLoginCorpCode</value>
      <webElementGuid>a0eb700f-1786-4646-882b-3dac3095be7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control uppercase allow-enter</value>
      <webElementGuid>09531d25-cf36-492f-b267-e0fe74505140</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d43a461a-0001-4093-9b37-d73cc58909a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex</name>
      <type>Main</type>
      <value>Invalid Character</value>
      <webElementGuid>eeeb3c4d-696d-4154-88c4-497440e04f36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex-pattern</name>
      <type>Main</type>
      <value>^\w+$</value>
      <webElementGuid>d08447f1-f9f1-4138-90fb-c4685d20b424</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Corp Code field is required.</value>
      <webElementGuid>ae681022-5744-43db-aa99-bf85f1a823dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Client_CorpCode</value>
      <webElementGuid>405797df-a724-48b6-a0b6-b91828960a74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Client.CorpCode</value>
      <webElementGuid>7c21acba-8cb3-4b31-be9b-c43ebed57391</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ddead16a-14b8-4080-9bf8-b14fe6da07aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Client_CorpCode&quot;)</value>
      <webElementGuid>76518111-9b64-42af-9b29-425093d7b0f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Client_CorpCode']</value>
      <webElementGuid>dee09abc-9206-448a-b6fb-7d33c1df5d73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='loginform']/div/div/form/div/div[2]/div/div[2]/div/input</value>
      <webElementGuid>47e24750-c602-4bfc-9cd0-386b61e41f59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>8d3172cb-7bdb-46f4-84d3-1a47ac7c0495</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Client_CorpCode' and @name = 'Client.CorpCode' and @type = 'text']</value>
      <webElementGuid>f2d3a556-5d63-4c0a-a9ba-df205496e9ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
