<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Invoices</name>
   <tag></tag>
   <elementGuidId>364c40e1-a696-4fb6-8cba-587f4d482513</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;ga('send', 'event', 'HomeMenus', 'click', 'Invoice');&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#billingContainer > div.section-title > a.menulink</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fadc5806-9211-4031-b9a5-6dd4bc599e11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>automation_id</name>
      <type>Main</type>
      <value>lnk_defaultBillingSubMenu</value>
      <webElementGuid>691d21aa-ae21-404a-9fc5-26bede7c15d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/SLQA/HS/Operations/Batch/ProcessInvoices</value>
      <webElementGuid>a6e74df5-7a1f-4da0-a588-5b5f7d6ed8ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menulink</value>
      <webElementGuid>0fa17ca7-ee76-45c7-8a74-e4693ae0af76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>ga('send', 'event', 'HomeMenus', 'click', 'Invoice');</value>
      <webElementGuid>a0afa49c-252e-4593-bac4-d3eaa762bf3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                                Invoices
                                                            </value>
      <webElementGuid>cc598a50-055d-4346-9bfd-ab4baf333667</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billingContainer&quot;)/div[@class=&quot;section-title&quot;]/a[@class=&quot;menulink&quot;]</value>
      <webElementGuid>3ff93bb2-d259-4a1d-a6f5-9f94adaab0ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;ga('send', 'event', 'HomeMenus', 'click', 'Invoice');&quot;]</value>
      <webElementGuid>f66e20cb-5bce-44de-8f8e-596de569875e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='billingContainer']/div/a</value>
      <webElementGuid>ad2efaf6-ca6c-4cda-9ba8-8e5b39d0dec4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Invoices')]</value>
      <webElementGuid>aab7be94-be86-4619-9b16-92854b93760e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Billing'])[1]/following::a[1]</value>
      <webElementGuid>0a82a6ed-0035-4d2a-91b8-63529d397799</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daily Close'])[1]/following::a[1]</value>
      <webElementGuid>49b7cc1b-e38b-4883-8e7c-d280ed563c06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ACH'])[1]/preceding::a[1]</value>
      <webElementGuid>11c8b890-dbe5-4a6e-8bd6-ca62907dcee8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Credit Cards'])[1]/preceding::a[2]</value>
      <webElementGuid>87998a66-5e39-41fb-acfa-b466f16b2411</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/SLQA/HS/Operations/Batch/ProcessInvoices')]</value>
      <webElementGuid>4ff4750a-0101-42af-b5b5-f767f0a1918a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/a</value>
      <webElementGuid>d47acd57-c529-4171-a253-fd5cce615824</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/SLQA/HS/Operations/Batch/ProcessInvoices' and (text() = '
                                                                Invoices
                                                            ' or . = '
                                                                Invoices
                                                            ')]</value>
      <webElementGuid>a9dd4173-7283-415d-992f-3647f6687685</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
