<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Merchandise</name>
   <tag></tag>
   <elementGuidId>ae655246-3bb4-4353-a06e-59733be2dd3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@onclick='dropdownClick(this)']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.menulink.collapsed</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6df8cd85-d016-495d-8357-97336bcf9c8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>automation_id</name>
      <type>Main</type>
      <value>div_defaultHubOperationsPageSubMenuDropdownLink</value>
      <webElementGuid>b6a5cb4f-572f-43fd-8f17-8d45c6958b89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menulink collapsed</value>
      <webElementGuid>c2a62e93-4268-4981-b4eb-5baf92ede120</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>74e23805-2d57-44d5-8296-06fc1ce9307c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>collapse</value>
      <webElementGuid>304afe3a-d07f-4a00-b0f1-488359126c1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>.collapse</value>
      <webElementGuid>efcc049c-a13d-485b-b28a-0aab2bc5cb82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8abf15ce-de26-4fe8-8ad3-c60bd5a4dbe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>dropdownClick(this)</value>
      <webElementGuid>6c132733-2787-4816-9a68-1d394fa3f10e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>Merchandise</value>
      <webElementGuid>553da1ff-925b-4be6-a49e-a472bc3229df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                                        Merchandise
                                                                    </value>
      <webElementGuid>70bf5c48-1de4-41be-9734-cc4e4d27837e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;operationsContainer&quot;)/div[@class=&quot;section-title&quot;]/div[1]/div[@class=&quot;menulink collapsed&quot;]</value>
      <webElementGuid>ddc362e0-cbd5-4a94-8ec1-453ae0c64866</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@onclick='dropdownClick(this)']</value>
      <webElementGuid>6908b8c3-49d6-4e7d-9195-432d91a4d8ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='operationsContainer']/div/div/div</value>
      <webElementGuid>f2cdd5d7-4c8d-4d0c-90fb-6acb9fd20e36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move Out'])[2]/following::div[2]</value>
      <webElementGuid>a733a60c-a2ca-4126-a90a-b4446c267207</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transfer'])[1]/following::div[2]</value>
      <webElementGuid>8994ded9-ca50-42f4-8f56-611b87ba3e2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Merchandise Purchase'])[1]/preceding::div[1]</value>
      <webElementGuid>fca1fdc0-57e8-4802-95d8-e02150572565</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Merchandise Return'])[1]/preceding::div[1]</value>
      <webElementGuid>ef4f5bd0-86bd-4bf1-9e33-b5bbea778a9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Merchandise']/parent::*</value>
      <webElementGuid>021d56c5-de2b-4fa4-bfd5-fff11ac19b06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div/div[2]/div/div/div/div</value>
      <webElementGuid>509f9cee-6258-4385-97ea-2ade0fa0e208</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
                                                                        Merchandise
                                                                    ' or . = '
                                                                        Merchandise
                                                                    ')]</value>
      <webElementGuid>f732b293-6070-479d-9ef8-a1cd3c7299fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
