<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_User Name_Client.UserName</name>
   <tag></tag>
   <elementGuidId>07496de6-8b17-4d7b-905b-6fb194ba1800</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Client_UserName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Client_UserName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7b0c109d-92be-4669-ba1f-5bc493df894c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>automation_id</name>
      <type>Main</type>
      <value>txt_clientLoginUserName</value>
      <webElementGuid>8f77682b-0a5e-4e27-9edf-7d6954394cf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control uppercase allow-enter</value>
      <webElementGuid>3109ce3a-2574-4a7f-8f50-efca8c92d025</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ea7a9879-3b19-4a91-97a4-f56abecee229</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The User Name field is required.</value>
      <webElementGuid>17561892-910b-4ed7-93ff-f766c2e6922e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Client_UserName</value>
      <webElementGuid>d0ff4313-9560-49e6-aba5-03876bf6c9e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Client.UserName</value>
      <webElementGuid>504139ca-2974-4b8d-920a-27e221d5f6a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>98dd8563-4076-42ee-a1b4-ce475253f80a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Client_UserName&quot;)</value>
      <webElementGuid>49caa7f6-e617-4504-aafa-53b4e3189299</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Client_UserName']</value>
      <webElementGuid>80462e09-a11f-4749-82c7-869325b8decd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='loginform']/div/div/form/div/div[2]/div/div[4]/div/input</value>
      <webElementGuid>8d594403-1963-40b1-b2b3-029e664de48c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>b488b3bd-4886-4ed2-9961-3f702d2ecccd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Client_UserName' and @name = 'Client.UserName' and @type = 'text']</value>
      <webElementGuid>85bced55-15b0-4edc-a726-8b6196d8ac7c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
