<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Payments</name>
   <tag></tag>
   <elementGuidId>90b826b3-66e8-40f7-9729-b69d65fe49cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;ga('send', 'event', 'HomeMenus', 'click', 'Payments');&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2fd48e90-829f-4d1a-9b65-c4c376f1d4eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>automation_id</name>
      <type>Main</type>
      <value>lnk_defaultOperationsSubMenu</value>
      <webElementGuid>6362f010-9da1-49a2-95cd-2d0ba875ddad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/SLQA/HS/Operations/Payment</value>
      <webElementGuid>2b28d5ae-204d-48f0-9c69-48dcbdc7d34a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> menulink</value>
      <webElementGuid>9166b48a-43ef-47cd-86d0-94a2c4e82580</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>ga('send', 'event', 'HomeMenus', 'click', 'Payments');</value>
      <webElementGuid>161c8480-3804-434e-81be-46783a4372a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                                    Payments
                                                                </value>
      <webElementGuid>8e22884a-c53f-4191-8303-e927a3fdff18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;operationsContainer&quot;)/div[@class=&quot;section-title&quot;]/a[@class=&quot;menulink&quot;]</value>
      <webElementGuid>406ab0be-2954-43df-bf9c-dffc0ac31b01</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;ga('send', 'event', 'HomeMenus', 'click', 'Payments');&quot;]</value>
      <webElementGuid>248ba017-b130-4689-8ec6-173b240554b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='operationsContainer']/div/a[2]</value>
      <webElementGuid>b0217fc9-bace-4d15-9746-6e4c871ebb59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Payments')]</value>
      <webElementGuid>bc962272-ff79-4d01-a5c3-2768840d9b71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lead to Lease'])[1]/following::a[1]</value>
      <webElementGuid>778a948d-077b-474e-aa76-d5cf4e6f25da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Operations'])[1]/following::a[2]</value>
      <webElementGuid>83d7bb7e-dbf9-452c-9c27-f607d2aa8aad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move In'])[1]/preceding::a[1]</value>
      <webElementGuid>1098720b-d51c-4ed6-9a8d-987eaddd6842</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transfer'])[1]/preceding::a[2]</value>
      <webElementGuid>fdf9ad82-1cd7-4971-8c62-716ccb172793</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Payments']/parent::*</value>
      <webElementGuid>4c55515e-ec9f-4b73-b6b1-0577e945c29b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/SLQA/HS/Operations/Payment')]</value>
      <webElementGuid>1d00ba8c-3b39-4723-85e6-d66750c42c05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>436c5f14-666e-435f-844c-a367a4fefa82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/SLQA/HS/Operations/Payment' and (text() = '
                                                                    Payments
                                                                ' or . = '
                                                                    Payments
                                                                ')]</value>
      <webElementGuid>ce57e198-15f4-48d6-ade3-af46c1e8cb91</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
