<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_Client.Password</name>
   <tag></tag>
   <elementGuidId>21e27cc0-97a4-4368-bc75-0878f8982467</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Client_Password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Client_Password</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9dc32ad6-b87a-45c0-8ce6-fd69e2dcd574</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>automation_id</name>
      <type>Main</type>
      <value>txt_clientLoginPassword</value>
      <webElementGuid>1e220b5e-18cd-4bc2-b8af-5d60bcc19ae4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-validation-error form-control</value>
      <webElementGuid>b44157b0-585d-4fdd-a882-3df37d7f24d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>066e80fb-4a86-485e-bae5-6cf3f2daecbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Password field is required.</value>
      <webElementGuid>c8206de2-8a2b-4f27-a311-e31d19786771</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Client_Password</value>
      <webElementGuid>7add7f1f-a40c-4124-b5b6-ec5a9983cfb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Client.Password</value>
      <webElementGuid>e1478309-f912-4939-9a75-85df06221130</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>700fa951-e543-40d8-85b6-abe439ddd137</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Client_Password&quot;)</value>
      <webElementGuid>f41dfd79-f7f0-4b4a-b0a8-105a8713cd09</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Client_Password']</value>
      <webElementGuid>aa6c619e-5f3e-41b7-b0cd-5d69c3210de2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='loginform']/div/div/form/div/div[2]/div/div[5]/div/input</value>
      <webElementGuid>ad4fbcb8-38b4-4b67-bc6b-0c4822af5e66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>5b38dc7e-9093-4cbe-b000-54486096e1be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Client_Password' and @name = 'Client.Password' and @type = 'password']</value>
      <webElementGuid>41efa82c-0b72-49e5-946e-36724339a6f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
