<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Invoices</name>
   <tag></tag>
   <elementGuidId>6abe0f0e-727c-4478-9c30-6b07e6f41d0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='InvoiceViewContainer']/div/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.page-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b8f2fc97-7014-40df-876f-7cd80ba9227a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page-title</value>
      <webElementGuid>2c706c58-6ac7-45e1-a6a1-109c9e7c7559</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Invoices</value>
      <webElementGuid>9b8848cc-e4b7-48cc-ac3b-476f15fed383</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;InvoiceViewContainer&quot;)/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;container-fluid full-height&quot;]/div[@class=&quot;row bottom-margin&quot;]/div[@class=&quot;col-md-6&quot;]/div[@class=&quot;page-title&quot;]</value>
      <webElementGuid>357288ec-2b33-40ad-86dd-3169c0cf902c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='InvoiceViewContainer']/div/div/div/div/div</value>
      <webElementGuid>88b7db05-aee9-40d9-a7c5-74742d8e0c13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='To Process (56)'])[1]/preceding::div[1]</value>
      <webElementGuid>b4240a44-5754-47a9-8cc8-f881d9b533e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unpaid (377)'])[1]/preceding::div[1]</value>
      <webElementGuid>640f132f-5ab4-4f78-ae79-742e19bb7fa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div</value>
      <webElementGuid>f4351af4-f633-4103-8584-3b3ba9a732fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Invoices' or . = 'Invoices')]</value>
      <webElementGuid>872e1ea6-9311-4ea8-a186-f32e28a2e240</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
