<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Transfer</name>
   <tag></tag>
   <elementGuidId>004e48f2-c4fd-4749-a42f-12c00046adaf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;ga('send', 'event', 'HomeMenus', 'click', 'Transfer');&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4217ea5e-d576-481b-9549-5422002e07cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>automation_id</name>
      <type>Main</type>
      <value>lnk_defaultOperationsSubMenu</value>
      <webElementGuid>6a37d414-c355-4f06-95b4-288848254960</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/SLQA/HS/Operations/Transfer</value>
      <webElementGuid>aab84792-b022-4ba3-be5f-855fb50aab59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> menulink</value>
      <webElementGuid>3839a652-3b0d-4225-8089-c87311043a6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>ga('send', 'event', 'HomeMenus', 'click', 'Transfer');</value>
      <webElementGuid>b302fb24-f9be-4526-bbf3-3fd6bac4f9de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                                    Transfer
                                                                </value>
      <webElementGuid>dbe766ba-947e-40cf-9c55-f81b5db37900</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;operationsContainer&quot;)/div[@class=&quot;section-title&quot;]/a[@class=&quot;menulink&quot;]</value>
      <webElementGuid>6d26c3fe-ad64-4809-81d4-aec4b4705d04</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;ga('send', 'event', 'HomeMenus', 'click', 'Transfer');&quot;]</value>
      <webElementGuid>8086518a-fb01-4316-961e-5710cc94c619</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='operationsContainer']/div/a[4]</value>
      <webElementGuid>76bd49e1-92db-44ae-aa67-62b9009f9a4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Transfer')]</value>
      <webElementGuid>5575e514-fbf6-4676-9f93-c451b1ee0bb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move In'])[1]/following::a[1]</value>
      <webElementGuid>91ce72f0-07ee-46e2-a5d0-eef7b73ce1ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payments'])[1]/following::a[2]</value>
      <webElementGuid>c6704e3c-4d8b-4d96-83f1-41ab664c3ca0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move Out'])[2]/preceding::a[1]</value>
      <webElementGuid>3c4de909-cb71-4dfc-95c7-c3d9f4e70334</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Merchandise'])[1]/preceding::a[2]</value>
      <webElementGuid>5894be6a-d003-4e27-87ca-787e4b81c1a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Transfer']/parent::*</value>
      <webElementGuid>d6a86b81-6968-4c6b-956a-36ab66dd4b38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/SLQA/HS/Operations/Transfer')]</value>
      <webElementGuid>bee2c928-e3bc-4204-aee9-56acbcab1a9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]</value>
      <webElementGuid>6b8e2d7f-25f3-48ad-9abd-16ee5fe1ee1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/SLQA/HS/Operations/Transfer' and (text() = '
                                                                    Transfer
                                                                ' or . = '
                                                                    Transfer
                                                                ')]</value>
      <webElementGuid>7c4ea882-ec20-4b8c-b48e-411c7e95e5d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
