<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Transactions</name>
   <tag></tag>
   <elementGuidId>fff4989d-8812-4f97-b08e-a02940deb85f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='phase0']/div/div/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#phase0 > div.col-sm-12 > div.section.blue > div.section-heading > span.cursor-pointer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1c8de262-07a0-452b-aedc-162e72055f04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>automation_id</name>
      <type>Main</type>
      <value>spn_achBatchTransactionsSectionSpan</value>
      <webElementGuid>b81055b7-18d6-4f31-81c6-1ece0861dab3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cursor-pointer</value>
      <webElementGuid>9366298c-4724-4aea-bea9-83d04b3a809b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>fnExpandPhase(0)</value>
      <webElementGuid>6133e1d7-0cee-4efd-aead-ab2461564081</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    
                                    Transactions
                                </value>
      <webElementGuid>c7e65c12-3980-4237-9e0f-e053ff458fb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;phase0&quot;)/div[@class=&quot;col-sm-12&quot;]/div[@class=&quot;section blue&quot;]/div[@class=&quot;section-heading&quot;]/span[@class=&quot;cursor-pointer&quot;]</value>
      <webElementGuid>b84c7559-3f21-4ed8-a5ee-d5f5b32a482a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='phase0']/div/div/div/span</value>
      <webElementGuid>28cb2fad-9da3-40fe-bea9-1842934189e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='To'])[1]/following::span[3]</value>
      <webElementGuid>640de805-3cf4-46f0-ae34-3de7c0377421</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ready To Submit (5)'])[1]/preceding::span[1]</value>
      <webElementGuid>8aa4b0ec-15d8-4ae1-9725-a463b7d513d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ready To Commit (0)'])[1]/preceding::span[1]</value>
      <webElementGuid>b962179a-32d3-45e2-9342-7590e25104b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Transactions']/parent::*</value>
      <webElementGuid>073f798b-aefd-4a57-8401-663f1a1be8f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div/div/div/span</value>
      <webElementGuid>c8970252-e246-4e0b-a4e9-ecbf6bd89a94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '
                                    
                                    Transactions
                                ' or . = '
                                    
                                    Transactions
                                ')]</value>
      <webElementGuid>12ce097c-b8e1-4e34-8981-36c7177bbd06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
