<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Location Code_Client.LocationCode</name>
   <tag></tag>
   <elementGuidId>c8834499-5e60-476a-a59a-ae493b9a1100</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Client_LocationCode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Client_LocationCode</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2321f4d3-552d-4cf4-b3d8-24d0457f02ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>automation_id</name>
      <type>Main</type>
      <value>txt_clientLoginLocationCode</value>
      <webElementGuid>3222aae7-e23a-4499-bc15-715204e49870</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control uppercase allow-enter</value>
      <webElementGuid>a89aae6d-297d-4d8d-828c-48fce3e8ce7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f5c9e5c7-fdcb-4156-a3a7-de471fe35b78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex</name>
      <type>Main</type>
      <value>Invalid Character</value>
      <webElementGuid>277e60f4-4ae4-4296-be58-dbf1d1c15fd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex-pattern</name>
      <type>Main</type>
      <value>^\w+$</value>
      <webElementGuid>551a0776-8adc-4765-b615-48655e3501af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Location Code field is required.</value>
      <webElementGuid>b42d7d21-31ba-4b0f-9a86-924f32588d11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Client_LocationCode</value>
      <webElementGuid>cc3fd0c9-2f94-47fc-aa8e-baf56f128ed3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Client.LocationCode</value>
      <webElementGuid>f129aa82-514c-4d82-b796-221580fe3c86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>815cb051-8af4-4c55-ad76-877a066b2009</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Client_LocationCode&quot;)</value>
      <webElementGuid>36b84bc4-1ddc-45f2-9db3-5f36d38e5758</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Client_LocationCode']</value>
      <webElementGuid>04e19e1a-1466-457f-afd6-68247496a938</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='loginform']/div/div/form/div/div[2]/div/div[3]/div/input</value>
      <webElementGuid>2918d1c9-d528-4863-930b-7686dbd0613f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>599ab96c-6293-4aa4-ac80-e9bcab48b890</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Client_LocationCode' and @name = 'Client.LocationCode' and @type = 'text']</value>
      <webElementGuid>4a80b6ca-4c6d-47e4-9cf5-3462877dc531</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
