<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_User Name_Client.UserName</name>
   <tag></tag>
   <elementGuidId>4825f2f3-435d-48a5-ab4b-3cdd6124f818</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Client_UserName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Client_UserName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8b8758d9-dff8-4a48-86c5-a0e54bed647c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>automation_id</name>
      <type>Main</type>
      <value>txt_clientLoginUserName</value>
      <webElementGuid>31559ade-8c51-4026-94dd-abb90b1c3c20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control uppercase allow-enter</value>
      <webElementGuid>10692315-df57-4eb7-bd2d-0e335daf988e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>48e1b3b2-2721-44c8-951d-6adc2c7a5ebf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The User Name field is required.</value>
      <webElementGuid>8c25b895-e6a4-4b52-9217-ae19949c44b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Client_UserName</value>
      <webElementGuid>f42e42ae-968c-4ff1-a0b6-1a39b115755d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Client.UserName</value>
      <webElementGuid>3e7c6315-7f0a-408f-ab73-d16c53285c2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4cd43c5f-a414-42d9-87a4-1b05da23ecea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Client_UserName&quot;)</value>
      <webElementGuid>de12c1b9-32f2-4a57-9f7c-c9231ac30f11</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Client_UserName']</value>
      <webElementGuid>e55620aa-c1ba-41f2-be8c-3fe2da428a72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='loginform']/div/div/form/div/div[2]/div/div[4]/div/input</value>
      <webElementGuid>d63ccc82-5810-4b65-9ec9-15f264933839</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>026d623e-2cef-49c8-88f4-ef39f66844f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Client_UserName' and @name = 'Client.UserName' and @type = 'text']</value>
      <webElementGuid>29e3fb83-e71c-43d4-8615-5e35e79f5b88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
