<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_btn btn-lg btn-block btn-primary</name>
   <tag></tag>
   <elementGuidId>b6a874ef-986e-4f4f-9a63-59ce4d20c0bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Login']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.btn.btn-lg.btn-block.btn-primary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>48697dc2-056a-4f89-9bb4-76d9af3809eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>automation_id</name>
      <type>Main</type>
      <value>btn_clientLoginSubmit</value>
      <webElementGuid>1c02a998-ef10-400b-a21f-92d6416a85ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>bb0bdbf1-7e7e-4d78-a532-b6779daa0e1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>b1ca0ba5-4399-48cc-bc00-0f63e9fa1ecd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-lg btn-block btn-primary</value>
      <webElementGuid>2747d47a-47f9-4a1a-8bc1-1ddeb7cfc202</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginform&quot;)/div[@class=&quot;row login-container&quot;]/div[@class=&quot;col-xs-12 col-sm-6 col-md-5 col-md-offset-1 slLoginPanel&quot;]/form[1]/div[@class=&quot;panel panel-primary&quot;]/div[@class=&quot;panel-footer&quot;]/input[@class=&quot;btn btn-lg btn-block btn-primary&quot;]</value>
      <webElementGuid>77299390-01d9-4ac8-9589-fc6323b14604</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Login']</value>
      <webElementGuid>641aacac-77ac-4f34-931d-c66933d38937</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='loginform']/div/div/form/div/div[3]/input</value>
      <webElementGuid>4cf65fd2-4734-4e99-9003-d7899cd39415</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>671f5367-70ad-49ac-9791-c651ff62443e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>2edfbf1c-de23-4590-a359-1aed40febb53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
